[window]

opacity = 0.9

padding.x = 2
padding.y = 2

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[font]

normal.family = "UbuntuMono Nerd Font Mono"
bold.family = "UbuntuMono Nerd Font Mono"
italic.family = "UbuntuMono Nerd Font Mono"
bold_italic.family = "UbuntuMono Nerd Font Mono"

size = 14.0

[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]
